#!/bin/sh -ex

PLATFORM=$1
OS=$2
VERSION=$3
ERLANG=$4
OUTPUT_DIR=$5

PACKAGE_REVISION=1 # TODO set this in makefile

# Ensure output dir exists
mkdir -p ${OUTPUT_DIR}

force_autoconf() {
    if grep update_configure otp_build; then
	./otp_build update_configure --no-commit
    else
	./otp_build autoconf
    fi
}

build_deb() {
    apt-get --quiet update && apt-get --quiet --yes install wget

    # setup build directory
    mkdir -p /opt/debuild
    wget -O - --no-verbose \
        https://github.com/erlang/otp/archive/OTP-${ERLANG}.tar.gz | \
	tar xzf - --strip-components=1 --directory=/opt/debuild
    cp --recursive in/debian /opt/debuild
    cd /opt/debuild

    # Try to add changes to changelog
    # Set adequate package version in changelog
    sed -i "s#@VSN@#${ERLANG}#g" debian/changelog

    # Set date in changelog
    DATE=$(date -R)
    sed -i "s#@DATE@#${DATE}#g" debian/changelog

    # Build the package
    force_autoconf
    debian/rules clean
    debian/rules build
    fakeroot debian/rules binary

    # Copy the artifacts out of the container
    cp /opt/*.deb ${OUTPUT_DIR}
}

build_centos() {
    # Download tarball
    download_tarball

    # setup build directory
    mkdir -p /opt/rpmbuild/SOURCES
    cp /opt/in/downloads/OTP-${ERLANG}.tar.gz /opt/rpmbuild/SOURCES/otp_src_${ERLANG}.tar.gz
    cp /opt/in/centos/.rpmmacros ~/
    cp --recursive /opt/in/centos/rpmbuild /opt
    cd /opt/
    export BUILDDIR=`pwd`
    HOSTNAME=`hostname`

    # Set erlang version in erlang.spec
    sed -i "s#@VER@#${ERLANG}#g" rpmbuild/SPECS/erlang.spec

    # Try to add changes to changelog
    DATE=$(date '+%a %b %d %Y')
    sed -i "s#@VSN@#${ERLANG}-${PACKAGE_REVISION}#g" rpmbuild/SPECS/erlang.spec
    sed -i "s#@DATE@#${DATE}#g" rpmbuild/SPECS/erlang.spec

    yum-builddep rpmbuild/SPECS/erlang.spec -y

    # Build the package
    cd rpmbuild
    spectool -g -R SPECS/erlang.spec
    rpmbuild -ba --define="revision ${ERLANG}" SPECS/erlang.spec

    # Copy the artifacts out of the container
    cp RPMS/$(arch)/*.rpm ${OUTPUT_DIR}
}

case "$OS-$VERSION" in
    debian*)
	build_deb
	break
	;;
    ubuntu*)
	build_deb
	break
	;;
    centos*)
	build_centos
	break
	;;
esac
