#!/bin/sh

ERLANG="21 22 23 24"
DEBIAN="stretch buster"
UBUNTU="trusty xenial bionic focal groovy hirsute"

for distro in $DEBIAN $UBUNTU
do
    for erlang in $ERLANG
    do
	aptly repo create $distro/erlang-$erlang
    done
done
