#!/bin/sh

case $1 in
    "linux/amd64")
	echo "amd64"
	;;
    "linux/arm/v5")
	echo "armel"
	;;
    "linux/arm/v7")
	echo "armhf"
	;;
    "linux/arm64" | "linux/arm64/v8")
	echo "arm64"
	;;
    "linux/mips64le")
	echo "mips64el"
	;;
    "linux/ppc64le")
	echo "ppc64el"
	;;
    "linux/s390x")
	echo "s390x"
	;;
    "linux/386")
	echo "i386"
	;;
    *)
	echo "unknown arch: $1" >&2
	exit 1
	;;
esac

exit 0
