# -*- mode: dockerfile -*-
# syntax = docker/dockerfile:1.2
ARG os
ARG os_version
FROM --platform=$BUILDPLATFORM $os:$os_version as builder
ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG os
ARG os_version

ENV DEBIAN_FRONTEND=noninteractive
ADD darch /usr/local/bin/

# Don't clean up
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache

# Install Erlang/OTP dependencies
RUN dpkg --add-architecture $(darch $TARGETPLATFORM)

# Cross-compilation setup for Ubuntu is a bit more involved...
RUN if [ "${os}" = "ubuntu" -a "${BUILDPLATFORM}" != "${TARGETPLATFORM}" ]; then \
    sed -i "s/deb http/deb [arch=$(darch $BUILDPLATFORM)] http/g" /etc/apt/sources.list; \
    echo "deb [arch=$(darch $TARGETPLATFORM)] http://ports.ubuntu.com/ubuntu-ports/ ${os_version} main universe" > /etc/apt/sources.list.d/cross.list; \
    echo "deb [arch=$(darch $TARGETPLATFORM)] http://ports.ubuntu.com/ubuntu-ports/ ${os_version}-updates main universe" >> /etc/apt/sources.list.d/cross.list; \
    echo "deb [arch=$(darch $TARGETPLATFORM)] http://ports.ubuntu.com/ubuntu-ports/ ${os_version}-security main universe" >> /etc/apt/sources.list.d/cross.list; \
    fi

# install WX dependencies from stretch-backports, if needed.
RUN --mount=type=cache,id=${os}_${os_version},target=/var/cache/apt,sharing=private \
    --mount=type=cache,id=${os}_${os_version},target=/var/lib/apt,sharing=private \
    if [ "${os}:${os_version}" = "debian:stretch" ]; then \
    echo "deb http://deb.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/stretch-backports.list; \
    apt-get --quiet update; \
    apt-get --quiet --yes --no-install-recommends install \
    libwxbase3.0-0v5:$(darch $TARGETPLATFORM)/stretch-backports \
    libwxbase3.0-dev:$(darch $TARGETPLATFORM)/stretch-backports \
    libwxgtk-webview3.0-gtk3-dev:$(darch $TARGETPLATFORM)/stretch-backports \
    libwxgtk3.0-gtk3-0v5:$(darch $TARGETPLATFORM)/stretch-backports \
    libwxgtk3.0-gtk3-dev:$(darch $TARGETPLATFORM)/stretch-backports \
    wx3.0-headers/stretch-backports; \
    fi

RUN --mount=type=cache,id=${os}_${os_version},target=/var/cache/apt,sharing=private \
    --mount=type=cache,id=${os}_${os_version},target=/var/lib/apt,sharing=private \
    apt-get --quiet update && apt-get --quiet --yes --no-install-recommends install \
    autoconf \
    build-essential \
    $(apt-cache show "crossbuild-essential-$(darch $TARGETPLATFORM)" > /dev/null 2>&1; \
    if [ $? -eq 0 ]; then \
      echo "crossbuild-essential-$(darch $TARGETPLATFORM)"; \
    fi) \
    ca-certificates \
    $(apt-cache show default-jdk-headless >/dev/null 2>&1; \
    if [ $? -eq 0 ]; then \
    echo "default-jdk-headless"; \
    else \
    echo "default-jdk"; \
    fi) \
    devscripts \
    flex \
    git \
    $(apt-cache show libwxgtk3.0-gtk3-dev >/dev/null 2>&1; \
    if [ $? -eq 0 ]; then \
    echo "libwxgtk3.0-gtk3-dev:$(darch $TARGETPLATFORM) libwxgtk-webview3.0-gtk3-dev:$(darch $TARGETPLATFORM)"; \
    else \
    echo "libwxgtk3.0-dev:$(darch $TARGETPLATFORM)"; \
    fi) \
    libncurses-dev:$(darch $TARGETPLATFORM) \
    libsctp-dev:$(darch $TARGETPLATFORM) \
    libssl-dev:$(darch $TARGETPLATFORM) \
    procps \
    unixodbc-dev:$(darch $TARGETPLATFORM) \
    wget \
    xsltproc

# Install FPM dependencies
RUN --mount=type=cache,id=${os}_${os_version},target=/var/cache/apt,sharing=private \
    --mount=type=cache,id=${os}_${os_version},target=/var/lib/apt,sharing=private \
    apt-get --quiet update && apt-get --quiet --yes --no-install-recommends install \
    ruby \
    ruby-dev

# Install FPM
RUN if [ "${os}:${os_version}" = "ubuntu:trusty" ]; then \
    gem install json --no-rdoc --no-ri --version 2.2.0; \
    gem install ffi --no-rdoc --no-ri --version 1.9.25; \
    gem install fpm --no-rdoc --no-ri --version 1.11.0; \
    else \
    gem install fpm --no-document --version 1.13.0; \
    fi

# Build it
WORKDIR /tmp/build
ARG erlang_version
RUN wget --quiet https://github.com/erlang/otp/releases/download/OTP-${erlang_version}/otp_src_${erlang_version}.tar.gz
RUN tar xf otp_src_${erlang_version}.tar.gz
ENV ERL_TOP=/tmp/build/otp_src_${erlang_version}
WORKDIR $ERL_TOP
RUN if [ ! -f configure ]; then \
    ./otp_build autoconf; \
    fi
# Bootstrap
RUN eval "$(dpkg-buildflags --export=sh)" && \
    ./configure --enable-bootstrap-only
ARG jobs
RUN make --jobs=${jobs}
RUN eval "$(dpkg-buildflags --export=sh)" && \
    ./configure \
    --host=$(dpkg-architecture -a $(darch $TARGETPLATFORM) -qDEB_TARGET_MULTIARCH) \
    erl_xcomp_sysroot=/ \
    --prefix=/usr \
    --enable-dirty-schedulers \
    --enable-dynamic-ssl-lib \
    --enable-kernel-poll \
    --enable-sctp \
    --with-java \
    --with-ssl

RUN make --jobs=${jobs}

# Test it
RUN if [ -f /usr/bin/hardening-check ]; then \
    hardening-check \
    --nobindnow \
    $(if [ "${os}:${os_version}" = "debian:bullseye" ]; then echo "--nocfprotection"; fi) \
    $(find $ERL_TOP -name erlexec); \
    fi

RUN make --jobs=${jobs} release_tests
WORKDIR $ERL_TOP/release/tests/test_server
RUN $ERL_TOP/bin/erl -noshell -s ts install -s ts smoke_test batch -s init stop
RUN if grep -q '=failed *[1-9]' ct_run.test_server@*/*/run.*/suite.log; then \
    echo "One or more tests failed."; \
    exit 1; \
    fi

WORKDIR $ERL_TOP
RUN make --jobs=${jobs} docs DOC_TARGETS="chunks man"
RUN mkdir -p /tmp/install
RUN make --jobs=${jobs} DESTDIR=/tmp/install install
RUN make --jobs=${jobs} DESTDIR=/tmp/install install-docs DOC_TARGETS="chunks man"

# Package it
WORKDIR /tmp/output
ARG erlang_iteration
RUN fpm -s dir -t deb \
    --chdir /tmp/install \
    --name esl-erlang \
    --version ${erlang_version} \
    --package-name-suffix ${os_version} \
    --architecture $(darch $TARGETPLATFORM) \
    --epoch 1 \
    --iteration ${erlang_iteration} \
    --package esl-erlang_VERSION-ITERATION~${os}~${os_version}_ARCH.deb \
    --maintainer "Erlang Solutions Ltd <support@erlang-solutions.com>" \
    --category interpreters \
    --description "Concurrent, real-time, distributed functional language" \
    --url "https://erlang-solutions.com" \
    --depends 'procps, libc6, libncurses5, libsctp1' \
    --depends $(apt-cache depends libssl-dev | grep Depends | grep -Eo 'libssl[0-9.]+') \
    $(if [ "${os}:${os_version}" != "ubuntu:trusty" ]; then echo '--deb-compression xz'; fi) \
    --deb-recommends 'libwxbase2.8-0 | libwxbase3.0-0 | libwxbase3.0-0v5, libwxgtk2.8-0 | libwxgtk3.0-0 | libwxgtk3.0-0v5 | libwxgtk3.0-gtk3-0v5' \
    --deb-suggests 'default-jre-headless | java2-runtime-headless | java1-runtime-headless | java2-runtime | java1-runtime' \
    $(for pkg in erlang-base-hipe erlang-base erlang-dev erlang-appmon erlang-asn1 erlang-common-test erlang-corba erlang-crypto erlang-debugger erlang-dialyzer erlang-docbuilder erlang-edoc erlang-erl-docgen erlang-et erlang-eunit erlang-gs erlang-ic erlang-inets erlang-inviso erlang-megaco erlang-mnesia erlang-observer erlang-odbc erlang-os-mon erlang-parsetools erlang-percept erlang-pman erlang-public-key erlang-reltool erlang-runtime-tools erlang-snmp erlang-ssh erlang-ssl erlang-syntax-tools erlang-test-server erlang-toolbar erlang-tools erlang-tv erlang-typer erlang-webtool erlang-wx erlang-xmerl; do \
    echo "--conflicts $pkg"; \
    echo "--replaces $pkg"; \
    echo "--provides $pkg"; \
    done) \
    .

# Export it
FROM scratch
COPY --from=builder /tmp/output /
