# syntax = docker/dockerfile:1.2
ARG platform

FROM --platform=$platform centos:7

# Install build dependencies
RUN --mount=type=cache,target=/var/cache/dnf,sharing=private --mount=type=cache,target=/var/cache/yum,sharing=private \
    yum install -y epel-release && yum install -y \
        make \
        git \
        deltarpm \
        autoconf \
        automake \
        bison \
        flex \
        ed \
        fop \
        java-devel \
        gcc \
        gcc-c++ \
        rpm-build \
        yum-utils \
        gpg \
        python-pip \
        rpm-sign \
        libxslt-devel \
        libxslt \
        ncurses-devel \
        openssl \
        openssl-devel \
        zlib-devel \
        m4 \
        unixODBC-devel \
        wxGTK-devel \
        tk-devel \
        tcl-devel \
        freeglut-devel \
        spectool \
        mesa-libGLU-devel \
        chrpath \
        curl \
        libtiff-devel && \
	yum clean all
