# syntax = docker/dockerfile:1.2
ARG os
ARG os_version
FROM $os:$os_version as builder
ARG os
ARG os_version
ADD yumdnf /usr/local/bin/

# Setup EPEL
RUN --mount=type=cache,id=${os}_${os_version},target=/var/cache/dnf,sharing=private \
    --mount=type=cache,id=${os}_${os_version},target=/var/cache/yum,sharing=private \
    yumdnf install -y epel-release

# Install Erlang/OTP dependencies
RUN --mount=type=cache,id=${os}_${os_version},target=/var/cache/dnf,sharing=private \
    --mount=type=cache,id=${os}_${os_version},target=/var/cache/yum,sharing=private \
    yumdnf install -y \
    autoconf \
    automake \
    bison \
    flex \
    gcc \
    gcc-c++ \
    git \
    java-11-openjdk-devel \
    libxslt-devel \
    libxslt \
    lksctp-tools-devel \
    make \
    ncurses-devel \
    openssl \
    openssl-devel \
    unixODBC-devel \
    wget \
    wxGTK3-devel \
    zlib-devel

# Install FPM dependences
RUN --mount=type=cache,id=${os}_${os_version},target=/var/cache/dnf,sharing=private \
    --mount=type=cache,id=${os}_${os_version},target=/var/cache/yum,sharing=private \
    yumdnf install -y \
    ruby-devel \
    gcc \
    make \
    rpm-build \
    libffi-devel

# Install FPM
RUN if [ "${os}:${os_version}" = "centos:7" ]; then \
    gem install git --no-document --version 1.7.0; \
    fi
RUN gem install fpm --no-document --version 1.12.0

# Build it
WORKDIR /tmp/build
ARG erlang_version
RUN wget --quiet https://github.com/erlang/otp/releases/download/OTP-${erlang_version}/otp_src_${erlang_version}.tar.gz
RUN tar xf otp_src_${erlang_version}.tar.gz
WORKDIR /tmp/build/otp_src_${erlang_version}
RUN if [ ! -f configure ]; then \
    ./otp_build autoconf; \
    fi
ENV CFLAGS="-g -O2 -fstack-protector-strong"
ENV LDFLAGS="-Wl,-z,relro"
RUN ./configure \
    --prefix=/usr \
    --enable-dirty-schedulers \
    --enable-dynamic-ssl-lib \
    --enable-kernel-poll \
    --enable-sctp \
    --with-java \
    --with-ssl

ARG jobs
RUN make --jobs=${jobs}
RUN make --jobs=${jobs} docs DOC_TARGETS="chunks man"
RUN mkdir -p /tmp/install
RUN make --jobs=${jobs} DESTDIR=/tmp/install install
RUN make --jobs=${jobs} DESTDIR=/tmp/install install-docs DOC_TARGETS="chunks man"

# Package it
WORKDIR /tmp/output
ARG erlang_iteration
RUN fpm -s dir -t rpm \
    --chdir /tmp/install \
    --name esl-erlang \
    --version ${erlang_version} \
    --package-name-suffix ${os_version} \
    --epoch 1 \
    --iteration ${erlang_iteration} \
    --package esl-erlang_VERSION_ITERATION~${os}~${os_version}_ARCH.rpm \
    --category interpreters \
    --description "Concurrent, real-time, distributed functional language" \
    --url "https://erlang-solutions.com" \
    --depends 'openssl-libs' \
    --provides "erlang = ${erlang_version}-${erlang_iteration}" \
    --provides "erlang-erts = ${erlang_version}-${erlang_iteration}" \
    --provides "erlang-inets = ${erlang_version}-${erlang_iteration}" \
    .

# Test it
RUN rpm -i /tmp/output/*.rpm
RUN erl -eval "ssl:start(), erlang:halt()."

# Export it
FROM scratch
COPY --from=builder /tmp/output /
