#!/bin/sh

ERLANG="21 22 23 24"
DEBIAN="stretch buster"
UBUNTU="trusty xenial bionic focal groovy hirsute"

for distro in $DEBIAN
do
    for erlang in $ERLANG
    do
	aptly publish repo -acquire-by-hash -distribution="$distro-erlang-$erlang" "$distro/erlang-$erlang" s3:test:debian/
    done
done

for distro in $UBUNTU
do
    for erlang in $ERLANG
    do
	aptly publish repo -acquire-by-hash -distribution="$distro-erlang-$erlang" "$distro/erlang-$erlang" s3:test:ubuntu/
    done
done
