#!/bin/bash
VER=$1
REV=$2
set -e
source common.sh

sudo apt-get install libxml2-utils chrpath
git clone bingen@autobot:otp-support.git
cd otp-support
git checkout ${VER}
_prog 10 "cloned repo"
./otp_build autoconf
_prog 15 "autoconf done"
./otp_build configure
_prog 25 "configure done"
./otp_build boot -a
_prog 40 "boot done"
./otp_build release -a
_prog 55 "release done!"
mkdir -p erlang/usr/lib/erlang erlang/usr/bin erlang/usr/etc erlang/usr/share
cp -r release/*/* erlang/usr/lib/erlang/
pushd erlang/usr/lib/erlang
./Install -cross -minimal /usr/lib/erlang
popd
pushd erlang
LINKDIR="../lib/erlang/usr/bin"
ln -s ${LINKDIR}/bin/{ct_run,dialyzer,epmd,erl,erlc,escript,run_erl,run_test,start_erl,to_erl,typer} usr/bin/
ln -s ${LINKDIR}/lib/{os_mon-*/priv/bin/cpu_sup,erl_interface-*/bin/erl_call} usr/bin/
ln -s ${LINKDIR}/lib/{observer-*/priv/bin/etop,observer-*/priv/bin/getop} usr/bin/
ln -s ${LINKDIR}/lib/{erlang/erts-*/bin/heart,os_mon-*/priv/bin/memsup,webtool-*/priv/bin/start_webtool} usr/bin/
popd

rm -rf erlang/usr/lib/erlang/lib/*/doc
mkdir -p erlang/usr/share/doc/esl-erlang/
cp EPLICENCE erlang/usr/share/doc/esl-erlang/copyright

set +e
for i in `find . -wholename '*/bin/*'`; do
    objdump -G ${i}
    RETVAL=$?
    [ $RETVAL -eq 0 ] && strip ${i}
done
set -e
find . -iname '*.so' -exec strip --strip-unneeded {} \;

sudo chrpath -d erlang/usr/lib/erlang/lib/crypto-*/priv/lib/crypto.so
sudo rm -rf erlang/usr/etc
sudo find erlang/ -name '.*' -delete
rm -rf erlang/usr/lib/erlang/man/cat*

mkdir -p erlang/DEBIAN
cp ../control erlang/DEBIAN/control
HOSTNAME=`hostname`
if [[ $HOSTNAME == *32 ]]; then
    ARCH="i386"
else
    ARCH="x86_64"
fi
sed -i "s#@VSN@#1:${VER}#" erlang/DEBIAN/control
sed -i "s#@ARCH@#${ARCH}#" erlang/DEBIAN/control

sudo chown -R root:root erlang/usr
set +e
find erlang/usr | sudo xargs chmod g-w
set -e
sudo mv erlang esl-erlang_${VER}-${REV}
sudo dpkg -b esl-erlang_${VER}-${REV}

_prog 80 "built. uploading"
mv esl-erlang_${VER}-${REV}.deb esl-erlang_${VER}-${REV}~${HOSTNAME}.deb
_upload esl-erlang_${VER}-${REV}~${HOSTNAME}.deb

_prog 100 "finished"
